### ISSUE TITLE
Two dead links in the Glossary

### ISSUE THREAD

**Issue by popuz** [decentraland/technical-documentation#108]
Links to the [Community Wiki](https://wiki.decentraland.org/index.php?title=About_Districts) in the **District** paragraph and to the [ERC-20 Token Standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md) in the **ERC20 Token** paragraph in the [Glossary](https://tech-docs.decentraland.org/player/general/glossary) page are dead.

**Comment by doomling** [comment]
Thanks for reporting!
@nearnshaw both dead links are external, where should I point those?

**Comment by nearnshaw** [comment]
I removed the mention to the first link, as it no longer exists
And changed the second link to the new equivalent
