### ISSUE TITLE
Doc tab leads to the old documentation

### ISSUE THREAD

**Issue by popuz** [decentraland/technical-documentation#110]
**Given** you are at the main https://tech-docs.decentraland.org/ page (or its sub-page)
**When** pressing _DOCS_ tab from the top menu
**Then** you redirected to the old https://docs.decentraland.org/
![image](https://user-images.githubusercontent.com/35366872/188977984-494b00af-4757-40b2-bf9a-f630ee833198.png)

Expected behavior: you browsed to the main https://tech-docs.decentraland.org/ page

**Comment by doomling** [comment]
intended, new docs will keep the currents docs domain
