### ISSUE TITLE
404 on some pages

### ISSUE THREAD

**Issue by nicorajco** [decentraland/technical-documentation#74]
This are some examples
https://tech-docs.decentraland.org/creator/werarables/linked-wearables
https://tech-docs.decentraland.org/creator/builder/builder-faq

<img width="913" alt="image" src="https://user-images.githubusercontent.com/66142960/178507849-9e0b1cb5-df94-4892-9279-e8eeb4abad74.png">

**Comment by LautaroPetaccio** [comment]
I'm adding a couple of other 404's:
- https://tech-docs.decentraland.org/creator/werarables/publishing-wearables
- https://tech-docs.decentraland.org/creator/werarables/curation-committee
- https://tech-docs.decentraland.org/creator/werarables/wearables-editor-user-guide
- https://tech-docs.decentraland.org/creator/development-guide/development-workflow
- https://tech-docs.decentraland.org/creator/development-guide/event-listeners
- https://tech-docs.decentraland.org/creator/blockchain-integration/create-a-dapp
And there might be more, would you mind checking all of them?

**Comment by doomling** [comment]
Fixed!
